export const DEFAULT_PROFILES = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    gender: "Male",
    genderTarget: "Female",
    matches: [],
    banned: false,
    age: 18,
    bio: "I like to code",
    preferences: ["tennis", "pizza", "voyages"],
    score: 10,
  },
  {
    name: "Alice Smith",
    email: "alice@gmail.com",
    gender: "Female",
    genderTarget: "Male",
    matches: [],
    banned: false,
    age: 25,
    bio: "Passionate about art and traveling",
    preferences: ["painting", "pizza", "voyages"],
    score: 12,
  },
  {
    name: "Bob Johnson",
    email: "bob@gmail.com",
    gender: "Male",
    genderTarget: "Female",
    matches: [],
    banned: false,
    age: 11,
    bio: "Love outdoor adventures",
    preferences: ["hiking", "pizza", "photography"],
    score: 20,
  },
  {
    name: "Carol Williams",
    email: "carol@gmail.com",
    gender: "Female",
    genderTarget: "Male",
    matches: [],
    banned: false,
    age: 22,
    bio: "Movie enthusiast and book lover",
    preferences: ["cinema", "reading", "tennis"],
    score: 12,
  },
  {
    name: "David Brown",
    email: "david@gmail.com",
    gender: "Male",
    genderTarget: "Female",
    matches: [],
    banned: false,
    age: 28,
    bio: "Tech geek, love programming and gaming",
    preferences: ["coding", "video games", "pizza"],
    score: 11,
  },
  {
    name: "Eva Davis",
    email: "eva@gmail.com",
    gender: "Female",
    genderTarget: "Male",
    matches: [],
    banned: false,
    age: 27,
    bio: "Yoga instructor, into healthy living",
    preferences: ["yoga", "vegan food", "traveling"],
    score: 12,
  },
  {
    name: "Frank Miller",
    email: "frank@gmail.com",
    gender: "Male",
    genderTarget: "Female",
    matches: [],
    banned: false,
    age: 24,
    bio: "Musician, love jazz and playing the guitar",
    preferences: ["music", "concerts", "pizza"],
    score: 12,
  },
  {
    name: "Grace Wilson",
    email: "grace@gmail.com",
    gender: "Female",
    genderTarget: "Male",
    matches: [],
    banned: false,
    age: 29,
    bio: "Graphic designer, passionate about art and creativity",
    preferences: ["design", "photography", "sushi"],
    score: 10,
  },
  {
    name: "Henry Moore",
    email: "henry@gmail.com",
    gender: "Male",
    genderTarget: "Female",
    matches: [],
    banned: false,
    age: 26,
    bio: "Engineer, love building things and problem-solving",
    preferences: ["engineering", "puzzles", "voyages"],
    score: 10,
  },
  {
    name: "Ivy Jackson",
    email: "ivy@gmail.com",
    gender: "Female",
    genderTarget: "Male",
    matches: [],
    banned: false,
    age: 20,
    bio: "Student, studying psychology and interested in people",
    preferences: ["psychology", "reading", "traveling"],
    score: 11,
  },
];
